#!/bin/sh

set -e

GITBLIT_PATH=/opt/gitblit
GITBLIT_HTTP_PORT=0
GITBLIT_HTTPS_PORT=8443
source ${GITBLIT_PATH}/java-proxy-config.sh
JAVA="java -server -Xmx1024M ${JAVA_PROXY_CONFIG} -Djava.awt.headless=true -jar"

. /lib/lsb/init-functions

case "$1" in
  start)
        log_action_begin_msg "Starting gitblit server"
        cd $GITBLIT_PATH
        $JAVA $GITBLIT_PATH/gitblit.jar --httpsPort $GITBLIT_HTTPS_PORT --httpPort $GITBLIT_HTTP_PORT > /dev/null &
        log_action_end_msg $?
        ;;
  stop)
        log_action_begin_msg "Stopping gitblit server"
        cd $GITBLIT_PATH
        $JAVA $GITBLIT_PATH/gitblit.jar --stop > /dev/null &
        log_action_end_msg $?
        ;;
  force-reload|restart)
        $0 stop
        $0 start
        ;;
  *)
        echo "Usage: /etc/init.d/gitblit {start|stop|restart|force-reload}"
        exit 1
        ;;
esac

exit 0
